organization:
    id: 0bfacf27-550c-4936-971c-51e842a287d7
    name: mfazz
project:
    id: 73c68fbb-5d38-4bfa-bbd5-07164e835196
    slug: circleci/2UoPcN4Qh7kBjW4oBPJhTC/FJCKZ56EaGmPLNgdFscAVb
    name: actuali
