name: Assign Issue

on:
  issue_comment:
    types: [created]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: takanome-dev/assign-issue-action@v3.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assign_command: "/assign-me"
          unassign_command: "/unassign-me"
          assigned_comment: "Thanks for taking this, issue has been assigned to you."
