name: Assign Issue

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: read

jobs:
  assign:
    if: github.repository == 'MattFaz/actuali'
    runs-on: ubuntu-latest
    steps:
      - uses: takanome-dev/assign-issue-action@v3.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          self_assign_cmd: "/assign-me"
          self_unassign_cmd: "/unassign-me"
          assigned_text: "Thanks @{{ handle }} for taking this, issue has been assigned to you."
          assigned_newcomer_text: "Thanks for jumping in @{{ handle }}, issue has been assigned to you. cc @MattFaz"
